// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKPaHWiTyaGJUu0XB2nGp6jRf1MIgHiYY',
    appId: '1:463658762955:web:b3ec36476d399beefdd14e',
    messagingSenderId: '463658762955',
    projectId: 'studyapp-ee3fc',
    authDomain: 'studyapp-ee3fc.firebaseapp.com',
    storageBucket: 'studyapp-ee3fc.appspot.com',
    measurementId: 'G-HKJGHW0683',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-eJjzO5aBxw8LT5ver2TKIxYAc8la6Ck',
    appId: '1:463658762955:android:9d5d20cf916c7faafdd14e',
    messagingSenderId: '463658762955',
    projectId: 'studyapp-ee3fc',
    storageBucket: 'studyapp-ee3fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBax5KhzHJ3X0ne5Zv1xkO4qBgw-XVc5T4',
    appId: '1:463658762955:ios:369512cda9784a4bfdd14e',
    messagingSenderId: '463658762955',
    projectId: 'studyapp-ee3fc',
    storageBucket: 'studyapp-ee3fc.appspot.com',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBax5KhzHJ3X0ne5Zv1xkO4qBgw-XVc5T4',
    appId: '1:463658762955:ios:22696cefa5318263fdd14e',
    messagingSenderId: '463658762955',
    projectId: 'studyapp-ee3fc',
    storageBucket: 'studyapp-ee3fc.appspot.com',
    iosBundleId: 'com.example.study.RunnerTests',
  );
}
