// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuuZHcnWMaJt2GwHkFsQ10nyQvCCkWTk',
    appId: '1:332831202170:web:55c02c85c859f9de1dd4c3',
    messagingSenderId: '332831202170',
    projectId: 'studyapp-2d1b2',
    authDomain: 'studyapp-2d1b2.firebaseapp.com',
    storageBucket: 'studyapp-2d1b2.appspot.com',
    measurementId: 'G-90YR19C5S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_m1qt1Hl52mw7ytXpHs2wT5cbAxMKuLI',
    appId: '1:332831202170:android:7b09855b6c2b6d901dd4c3',
    messagingSenderId: '332831202170',
    projectId: 'studyapp-2d1b2',
    storageBucket: 'studyapp-2d1b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9WXgL48iftoJOZWxsvsVC1F5_5ZYDdnE',
    appId: '1:332831202170:ios:a6c91b6f0add90cc1dd4c3',
    messagingSenderId: '332831202170',
    projectId: 'studyapp-2d1b2',
    storageBucket: 'studyapp-2d1b2.appspot.com',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9WXgL48iftoJOZWxsvsVC1F5_5ZYDdnE',
    appId: '1:332831202170:ios:3595dde26bb560671dd4c3',
    messagingSenderId: '332831202170',
    projectId: 'studyapp-2d1b2',
    storageBucket: 'studyapp-2d1b2.appspot.com',
    iosBundleId: 'com.example.study.RunnerTests',
  );
}
